{{- if .Values.certificates.enabled -}}
{{- range $host := .Values.ingress.hosts }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name:  {{ include "corona-backend.name" $ }}-{{ $host | replace "." "-" }}-cert
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "corona-backend.labels" $ | nindent 4 }}
spec:
  secretName: {{ include "corona-backend.name" $ }}-{{ $host | replace "." "-" }}-secret
  issuerRef:
    name: {{ include "corona-backend.certificateIssuer" $ }}
    {{- if eq (lower $.Values.certificates.issuer) "external" }}
    kind: {{ $.Values.certificates.externalIssuerKind }}
    {{- end }}
  commonName: {{ $host }}
  dnsNames:
    - {{ $host }}
    #- www.{{ $host }}
{{- end }}
{{- end }}