apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ATEMPLATE.name" . }}-environment
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "ATEMPLATE.labels" . | nindent 4 }}
data:
  NODE_ENV: production