apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corona-backend.name" . }}-environment
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "corona-backend.labels" . | nindent 4 }}
data:
  NODE_ENV: production