apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gc-chat.name" . }}-environment
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "gc-chat.labels" . | nindent 4 }}
data:
  NODE_ENV: production