{{- if .Values.image.fromGcHub }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gc-chat.name" . }}-docker-config
  namespace: {{.Release.Namespace}}
  labels:
    {{- include "gc-chat.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ include "gc-chat.docker-config" . }}
type: kubernetes.io/dockerconfigjson
{{- end }}