{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "ATEMPLATE.name" . }}-ingress
  namespace: {{.Release.Namespace}}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    {{- include "ATEMPLATE.labels" . | nindent 4 }}
spec:
  {{ if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ . | quote }}
      secretName: {{ include "ATEMPLATE.name" $ }}-{{ . | replace "." "-" }}-secret
    {{- end }}
  {{ end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "ATEMPLATE.name" $ }}-service
              servicePort: 80
  {{- end }}
{{- end }}