{{- if .Values.traefik.crds -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "ATEMPLATE.name" . }}-strip-version-prefix-middleware
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ATEMPLATE.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /v{{ include "ATEMPLATE.version" . }}
{{- end }}