{{- if .Values.traefik.crds -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "ATEMPLATE.name" . }}-https-only-middleware
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ATEMPLATE.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
{{- end }}