{{- if .Values.traefik.crds -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "gc-chat.name" . }}-strip-version-prefix-middleware
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gc-chat.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /v{{ include "gc-chat.version" . }}
{{- end }}