#kubectl create namespace gc-chat
#kubectl config set-context --current --namespace=gc-chat
#helm install --debug gc-chat ./helm --namespace=gc-chat
#helm uninstall gc-chat

#kubectl create namespace gc-chat-1-0-0
#kubectl config set-context --current --namespace=gc-chat-1-0-0
#helm install --dry-run gc-chat ./helm --namespace=gc-chat-1-0-0 --set ingress.hosts\[0\]=gc-chat.gamechange.dev,externalNats.host=nats-client.nats.svc.cluster.local
#helm install gc-chat ./helm --namespace=gc-chat-1-0-0 --set ingress.hosts\[0\]=gc-chat.gamechange.dev,externalNats.host=nats-client.nats.svc.cluster.local,replicaCount=1

#helm upgrade --dry-run gc-chat ./helm --namespace=gc-chat --set ingress.hosts\[0\]=gc-chat.gamechange.dev,externalNats.host=nats-client.nats.svc.cluster.local,image.versionOverride=1.0.9
#helm install gc-chat ./helm --namespace=gc-chat --set ingress.hosts\[0\]=gc-chat.gamechange.dev,externalNats.host=nats-client.nats.svc.cluster.local,replicaCount=1
#helm install gc-chat ./helm --namespace=gc-chat --set ingress.hosts\[0\]=gc-chat.gamechange.dev,externalNats.host=nats-client.nats.svc.cluster.local,replicaCount=1,image.versionOverride={{}},image.gcCredentials.username={{}},image.gcCredentials.password={{}}

apiVersion: v2
name: gc-chat
description: A helm chart for gc-chat kubernetes deployment
type: application

sources:
  - https://github.com/gcsns/gc-chat
maintainers:
  - name: K V Adhityan
    email: adhityan@gamechangesns.com

dependencies:
  # - name: nats
  #   version: 4.x.x
  #   repository: https://kubernetes-charts.storage.googleapis.com/
  #   condition: nats.enabled

version: 1.0.1
appVersion: 1.0.0
