#kubectl create namespace ATEMPLATE
#kubectl config set-context --current --namespace=ATEMPLATE
#helm install --debug ATEMPLATE ./helm --namespace=ATEMPLATE

#helm install ATEMPLATE ./helm --namespace=ATEMPLATE --set ingress.hosts\[0\]=ATEMPLATE.gamechange.dev
#helm install --dry-run ATEMPLATE ./helm --namespace=ATEMPLATE --set ingress.hosts\[0\]=ATEMPLATE.gamechange.dev
#helm upgrade --dry-run ATEMPLATE ./helm --namespace=ATEMPLATE --set ingress.hosts\[0\]=ATEMPLATE.gamechange.dev
#helm uninstall ATEMPLATE

apiVersion: v1
name: ATEMPLATE
description: A helm chart for ATEMPLATE kubernetes deployment
type: application

dependencies:

sources:
  - https://github.com/adhityan/node-microsite-template

maintainers:
  - name: K V Adhityan
    email: adhityan@gamechangesns.com

version: 1.0.0
appVersion: 1.0.0